language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm

script:
  - phpunit --coverage-clover build/logs/clover.xml

services:
  - elasticsearch

before_script:
  - composer install
  - sleep 10

after_success:
  - travis_retry php vendor/bin/coveralls -v