language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

services:
  - elasticsearch

before_script:
  - composer install
  - sleep 10

after_success:
  - travis_retry php vendor/bin/coveralls -v
